server:
  port: 9090
  servlet:
    context-path: /api_template/v1
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: localImages