server:
  port: 9091
  servlet:
    context-path: /api_template/v1
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
